# Generated by Django 3.0.5 on 2020-04-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_rss_feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsssource',
            name='last_build_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
