# Generated by Django 3.0.5 on 2020-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_rss_feeds', '0002_auto_20200420_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeedarticle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rssfeedarticle',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rssfeedarticle',
            name='last_refresh',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rssfeedarticle',
            name='pubdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='last_build_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='last_refresh',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
